services:
  app:
    image: icub-skin-container:latest
    container_name: icub-skin
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    tty: true
    stdin_open: true