version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ${USER}
        uid:  ${UID}
        gid:  ${GID}
    network_mode: host
    tty: true
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 6